<!-- サイドバーとしてよみこまれるHTML -->
<div>
  <h2>Menu</h2>
</div>
<div>
  <h3>ハンバーガー</h3>
  <ul>
    <li>ハンバーガー</li>
    <li>チーズバーガー</li>
    <li>テリヤキバーガー</li>
    <li>アボガドバーガー</li>
    <li>ベーコンバーガー</li>
    <li>チキンバーガー</li>
  </ul>
</div>

<div>
  <h3>サイドメニュー</h3>
  <ul>
    <li>ポテト</li>
    <li>サラダ</li>
    <li>ナゲット</li>
    <li>コーン</li>
  </ul>
</div>
<div>
  <h3>ドリンク</h3>
  <ul>
    <li>コーラ</li>
    <li>ファンタ</li>
    <li>オレンジ</li>
    <li>アップル</li>
    <li>紅茶（Ice/Hot）</li>
    <li>コーヒー（Ice/Hot）</li>
  </ul>
</div>